# -*- coding: utf-8 -*-
"""IRIS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ad6_UDvgPTrwalABnqRh4bLeyg0T0888
"""

#imorting packages
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn import svm
from sklearn.model_selection import GridSearchCV

#Loading Dataset
dataframe=pd.read_csv("spam.csv")
print(dataframe.describe())

#Split into Training & Testing Dataset
x=dataframe["EmailText"]
y=dataframe['Label']

x_train,y_train=x[0:4400],y[0:4400]
x_test,y_test=x[4400:],y[4400:]

#Extract Features
cv=CountVectorizer()
features=cv.fit_transform(x_train)

#Hypertuning Parameters
tuned_parameters = {'kernel:['}

#Building a model
model=svm.SVC()
model.fit(features,y_train)

#Testing Accuracy
features_test = cv.transform(x_test)
print("Accuracy of the model is:",model.score(features_test,y_test))

tuned_parameters = {'kernel':['linear','rbf'],'gamma':[1e-3,1e-4],'C':[1,10,100,1000]}
model = GridSearchCV(svm.SVC(),tuned_parameters)
model.fit(features,y_train)

print(model.best_params_)
features_test = cv.transform(x_test)
print("Accuracy of the model is:",model.score(features_test,y_test))

from sklearn.model_selection import RandomizedSearchCV
tuned_parameters = {'kernel':['linear','rbf'],'gamma':[1e-3,1e-4],'C':[1,10,100,1000]}
model = RandomizedSearchCV(svm.SVC(),tuned_parameters)
model.fit(features,y_train)

pd.DataFrame(model.cv_results_)[['param_C','param_kernel','mean_test_score']]